name: Move and unlabel ready to merge issues
on:
  issues:
    types:
      - labeled

jobs:
  unmark_for_review:
    if: github.repository == 'github/docs' && github.event.label.name == 'ready to merge'
    runs-on: ubuntu-latest
    steps:
      - name: move issue
        uses: alex-page/github-project-automation-plus@fdb7991b72040d611e1123d2b75ff10eda9372c9
        with:
          project: Docs team reviews
          column: Triage
          repo-token: ${{ secrets.DOCUBOT_FR_PROJECT_BOARD_WORKFLOWS_REPO_ORG_READ_SCOPES }}
      - name: remove label
        uses: andymckay/labeler@22d5392de2b725cea4b284df5824125054049d84
        with:
          remove-labels: 'waiting for review'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
