name: Move help wanted issues
on:
  issues:
    types:
      - labeled

jobs:
  move_issues:
    if: github.repository == 'github/docs' && (github.event.label.name == 'help wanted' || github.event.label.name == 'good first issue')
    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@fdb7991b72040d611e1123d2b75ff10eda9372c9
        with:
          project: Docs team reviews
          column: Help wanted
          repo-token: ${{ secrets.DOCUBOT_FR_PROJECT_BOARD_WORKFLOWS_REPO_ORG_READ_SCOPES }}
